server:
  port: 8084
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /staffs/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
            
            
 #okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-39965752.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaihzmhpv04rcaHY5d7
    client-secret: 17YLDvHwT_5xH9yQLy6eOW2TN0yYJApG7Bb_0CRBAHVaGaActmtirdQY6QSs3Poh
    scopes: openid, profile, email, offline_access